### ISSUE TITLE
Call to undefined function error

### ISSUE THREAD

**Issue by aydnbhdr** [alexsoft/Laravel-Pusher#1]
When  I try to trigger anything I got this error: 
```
FatalErrorException in Facade.php line 216:
Call to undefined method Alexsoft\LaravelPusher\Facades\Pusher::trigger()
```

I am using it on WelcomeController with:
```
use Pusher;
```

And try to trigger it with at index() function
```
Pusher::trigger( 'my-channel', 'my_event', 'hello world' );
```

**Comment by alexsoft** [comment]
@aydnbhdr if you made an alias in `config/app.php` file then you should
`use \Pusher;`
If not then
`use Alexsoft\LaravelPusher\Facades\Pusher;`

**Comment by aydnbhdr** [comment]
I did it on config/app.php as 
````
'Pusher'    => 'Alexsoft\LaravelPusher\Facades\Pusher',
```
The error still occurs same as at this url: https://github.com/vinkla/pusher/issues/2

**Comment by yhalabi** [comment]
Same Issue

**Comment by yhalabi** [comment]
i dont know if this helps
    
```php
Route::get('push',function(){
	$pusher = new Pusher;
	var_dump($pusher);
});
```
generates

```php
object(Alexsoft\LaravelPusher\Facades\Pusher)#247 (0) { } 
```

**Comment by alexsoft** [comment]
@aydnbhdr @yhalabi I found the issue.
The issue is that the real Pusher class which works with API is in root namespace. That means that you need to name alias differently.
e.g. in config/app.php
```
'LaravelPusher'    => 'Alexsoft\LaravelPusher\Facades\Pusher',
```

**Comment by alexsoft** [comment]
In any case I suggest using https://github.com/vinkla/pusher
